// Local commentary source identities for app.bible.
// These names are intentionally stable and repo-local so the app does not
// depend on remote query keywords or external URL shapes.

export default [
  {
    id: 'spurgeon_verse_expositions',
    scriptName: 'commentarySpurgeonVerseExpositions',
    modulePath: './sources/commentary-spurgeon-verse-expositions.js',
    worlddicCode: 'Spur_Ex',
    name: "Spurgeon's Verse Expositions",
    keyword: 'Spur Ex',
  },
  {
    id: 'spurgeon_sermons',
    scriptName: 'commentarySpurgeonSermons',
    modulePath: './sources/commentary-spurgeon-sermons.js',
    worlddicCode: 'Spurgeon_Ser',
    name: "Spurgeon's Sermons",
    keyword: 'Spurgeon Ser',
  },
  {
    id: 'spurgeon_daily_devotion',
    scriptName: 'commentarySpurgeonDailyDevotion',
    modulePath: './sources/commentary-spurgeon-daily-devotion.js',
    worlddicCode: 'Spurgeon_Daily',
    name: "Spurgeon's Daily Devotion",
    keyword: 'Spurgeon Daily',
  },
  {
    id: 'matthew_henry_complete',
    scriptName: 'commentaryMatthewHenryComplete',
    modulePath: './sources/commentary-matthew-henry-complete.js',
    worlddicCode: 'Matt_Hen_Wh',
    name: "Matthew Henry's Complete",
    keyword: 'Matt Hen Wh',
  },
  {
    id: 'matthew_henry_concise',
    scriptName: 'commentaryMatthewHenryConcise',
    modulePath: './sources/commentary-matthew-henry-concise.js',
    worlddicCode: 'Matt_Hen_Con',
    name: "Matthew Henry's Concise",
    keyword: 'Matt Hen Con',
  },
  {
    id: 'calvin_commentary',
    scriptName: 'commentaryCalvin',
    modulePath: './sources/commentary-calvin.js',
    worlddicCode: 'Calvin',
    name: "Calvin's Commentary",
    keyword: 'Calvin',
  },
  {
    id: 'pulpit_commentaries',
    scriptName: 'commentaryPulpitCommentaries',
    modulePath: './sources/commentary-pulpit-commentaries.js',
    worlddicCode: 'Pulpit',
    name: 'The Pulpit Commentaries',
    keyword: 'Pulpit',
  },
  {
    id: 'scofield_reference_notes',
    scriptName: 'commentaryScofieldReferenceNotes',
    modulePath: './sources/commentary-scofield-reference-notes.js',
    worlddicCode: 'Scofield',
    name: "Scofield's Reference Notes",
    keyword: 'Scofield',
  },
  {
    id: 'wesley_explanatory_notes',
    scriptName: 'commentaryWesleyExplanatoryNotes',
    modulePath: './sources/commentary-wesley-explanatory-notes.js',
    worlddicCode: 'Wesley',
    name: "Wesley's Explanatory Notes",
    keyword: 'Wesley',
  },
  {
    id: 'adam_clarke_commentary',
    scriptName: 'commentaryAdamClarke',
    modulePath: './sources/commentary-adam-clarke.js',
    worlddicCode: 'Adam_Cla',
    name: 'Adam Clarke Commentary',
    keyword: 'Adam Cla',
  },
  {
    id: 'albert_barnes_notes',
    scriptName: 'commentaryAlbertBarnesNotes',
    modulePath: './sources/commentary-albert-barnes-notes.js',
    worlddicCode: 'Albert_Bar',
    name: "Albert Barnes' Notes",
    keyword: 'Albert',
  },
  {
    id: 'joseph_benson_commentary',
    scriptName: 'commentaryJosephBenson',
    modulePath: './sources/commentary-joseph-benson.js',
    worlddicCode: 'Joseph_Ben',
    name: "Joseph Benson's Commentary",
    keyword: 'Joseph',
  },
  {
    id: 'bridgeway_bible_commentary',
    scriptName: 'commentaryBridgewayBible',
    modulePath: './sources/commentary-bridgeway-bible.js',
    worlddicCode: 'Bridgeway',
    name: 'The Bridgeway Bible Commentary',
    keyword: 'Bridgeway',
  },
  {
    id: 'ew_bullinger_companion',
    scriptName: 'commentaryEwBullingerCompanion',
    modulePath: './sources/commentary-ew-bullinger-companion.js',
    worlddicCode: 'Bullinger',
    name: "E.W. Bullinger's Companion",
    keyword: 'Bullinger',
  },
  {
    id: 'thomas_constable_notes',
    scriptName: 'commentaryThomasConstableNotes',
    modulePath: './sources/commentary-thomas-constable-notes.js',
    worlddicCode: 'Dr_Thomas',
    name: 'Thomas Constable',
    keyword: 'Dr Thomas',
  },
  {
    id: 'thomas_coke_commentary',
    scriptName: 'commentaryThomasCoke',
    modulePath: './sources/commentary-thomas-coke.js',
    worlddicCode: 'Thomas_Coke',
    name: 'Thomas Coke Commentary',
    keyword: 'Thomas Coke',
  },
  {
    id: 'john_gill_exposition',
    scriptName: 'commentaryJohnGillExposition',
    modulePath: './sources/commentary-john-gill-exposition.js',
    worlddicCode: 'John_Gill',
    name: "John Gill's Exposition",
    keyword: 'John Gill',
  },
  {
    id: 'commentary_critical_explanatory',
    scriptName: 'commentaryCriticalExplanatory',
    modulePath: './sources/commentary-critical-explanatory.js',
    worlddicCode: 'Critical_Expl',
    name: 'Commentary Critical and Explanatory',
    keyword: 'Critical',
  },
  {
    id: 'john_dummelow_commentary',
    scriptName: 'commentaryJohnDummelow',
    modulePath: './sources/commentary-john-dummelow.js',
    worlddicCode: 'John_Dum',
    name: "John Dummelow's Commentary",
    keyword: 'John Dum',
  },
  {
    id: 'geneva_study_bible',
    scriptName: 'commentaryGenevaStudyBible',
    modulePath: './sources/commentary-geneva-study-bible.js',
    worlddicCode: 'Geneva_Stu',
    name: 'Geneva Study Bible',
    keyword: 'Geneva',
  },
  {
    id: 'ellicott_commentary',
    scriptName: 'commentaryEllicott',
    modulePath: './sources/commentary-ellicott.js',
    worlddicCode: 'Ellicott',
    name: "Ellicott's Commentary",
    keyword: 'Ellicott',
  },
  {
    id: 'arno_gaebelein_annotated_bible',
    scriptName: 'commentaryArnoGaebeleinAnnotatedBible',
    modulePath: './sources/commentary-arno-gaebelein-annotated-bible.js',
    worlddicCode: 'Arno_Gae',
    name: "Arno Gaebelein's Annotated Bible",
    keyword: 'Arno',
  },
  {
    id: 'james_gray_commentary',
    scriptName: 'commentaryJamesGray',
    modulePath: './sources/commentary-james-gray.js',
    worlddicCode: 'James_Gray',
    name: 'James Gray',
    keyword: 'James',
  },
];
